export const CHANGE_PLAY_SONG_DETAIL_INFO = "songDetail/CHANGE_PLAY_SONG_DETAIL_INFO"
export const CHANGE_PLAY_SONG_URL = "songDetail/CHANGE_PLAY_SONG_URL"

export const CHANGE_PLAY_SONG_LIST = "songDetail/CHANE_PLAY_SONG_LIST"
export const CHANGE_CURRENT_PLAY_SONG_INDEX= "songDetail/CHANGE_CURRENT_PLAY_SONG_INDEX"
export const CHANGE_CURRENT_PATTERN= "songDetail/CHANGE_CURRENT_PATTERN"
export const CHANGE_SONG_LYRIC = "songDetail/CHANGE_SONG_LYRIC"